-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS app_db.events
(
    "EVENT_ID" integer NOT NULL,
    "DESCRIPTION" text NOT NULL,
    PRIMARY KEY ("EVENT_ID")
);

CREATE TABLE IF NOT EXISTS app_db.events_logs
(
    "EVENT_DATE" timestamp without time zone NOT NULL,
    "USER_ID" character(100) NOT NULL,
    "EVENT_ID" integer NOT NULL,
    "EVENT_VALUE" double precision,
    "PARAMS" text,
    "ID" bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 0 MINVALUE 0 MAXVALUE 1000000 CACHE 1 ),
    PRIMARY KEY ("ID")
);

ALTER TABLE app_db.events_logs
    ADD FOREIGN KEY ("EVENT_ID")
    REFERENCES app_db.events ("EVENT_ID")
    NOT VALID;

END;